# fly.toml app configuration file generated for backend-calendar-app on 2023-07-16T23:20:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-calendar-app"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
